server:
  port: 8090
spring:
  application:
    name: ComputerShop
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/computer_shop?serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    generate-ddl: false
    show-sql: false
    hibernate:
      ddl-auto: validate
  jackson:
    serialization:
      fail-on-empty-beans: false
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size:  200MB
      max-request-size: 250MB
jwt:
  security:
    key: qwerty
    expired: 3600000

